build:
	docker build . -f Dockerfile.fluentbit  -t fluent-bit-test:latest

run:
	docker run -it fluent-bit-test:latest /bin/bash
	# /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/application.conf を手動実行

